from routes.frontend.home import *
from routes.frontend.product import *
from routes.frontend.shop import *
from routes.frontend.contact import *
from routes.frontend.checkout import *
from routes.frontend.cart import *
from routes.error import *
from routes.frontend.mail import *
from routes.admin.user import *